trigger: none
pool: agentpool111
steps:
  - 
- task: TerraformInstaller@2
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformCLI@2
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'PR2- CI- Service Connection'
    backendAzureRmStorageAccountName: 'sumantstrg'
    backendAzureRmContainerName: 'sumantcontainer'
    backendAzureRmKey: 'sumant.tfstate'
    allowTelemetryCollection: true
- task: TerraformCLI@2
  inputs:
    command: 'validate'
    allowTelemetryCollection: true